name: First Workflow 
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greeting
        run: |
            echo "Hello World!"
            echo "Hello Universe!"
            echo "Hello Nation!"
      - name: print goodbye
        run: echo "Done - Bye!"

